version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_web
    ports:
      - "8080:80"
  database:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensors
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mysql_data:
  
